[package]
name = "cacutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.2"
whoami = "0.8.2"
sys-info = "0.8.0"
chrono = "0.4.19"